---
# This role installs Java and configures $JAVA_HOME.

- name: Install Java
  yum:
    name: java-11-openjdk-devel.x86_64
    state: installed

- name: Java_home
  shell: echo "export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >/etc/profile.d/java_home.sh
  when:
    -  '"/etc/profile.d/java_home.sh" is not exists'